version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: dev.Dockerfile
    volumes:
      - ./:/backend
    ports:
      - "80:80"

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    volumes:
      - ./redis/redis-data:/var/lib/redis
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_REPLICATION_MODE=master
